#pragma once

#include <memory>
#include <string>
#include <variant>

#include "Token.h"

// ------------------------------------------------------------
// This file is auto-generated by GenerateAst.
// Do not edit manually.
// ------------------------------------------------------------

