#pragma once

#include <memory>
#include <string>
#include <variant>

#include "scanner/Token.h"

// ------------------------------------------------------------
// This file is auto-generated by GenerateAst.
// Do not edit manually.
// ------------------------------------------------------------


class Binary : public Expr
{
    public:
        Binary(
            std::unique_ptr<Expr> left,
            Token op,
            std::unique_ptr<Expr> right
        );


    private:
        std::unique_ptr<Expr> left_;
        Token op_;
        std::unique_ptr<Expr> right_;
    void accept(ExprVisitor& visitor) const override
    {
        visitor.visitBinaryExpr(*this);
    }

};

class Grouping : public Expr
{
    public:
        Grouping(
            std::unique_ptr<Expr> expression
        );


    private:
        std::unique_ptr<Expr> expression_;
    void accept(ExprVisitor& visitor) const override
    {
        visitor.visitGroupingExpr(*this);
    }

};

class Literal : public Expr
{
    public:
        Literal(
            LiteralValue value
        );


    private:
        LiteralValue value_;
    void accept(ExprVisitor& visitor) const override
    {
        visitor.visitLiteralExpr(*this);
    }

};

class Unary : public Expr
{
    public:
        Unary(
            Token op,
            std::unique_ptr<Expr> right
        );


    private:
        Token op_;
        std::unique_ptr<Expr> right_;
    void accept(ExprVisitor& visitor) const override
    {
        visitor.visitUnaryExpr(*this);
    }

};


class Expr
{
public:
    virtual ~Expr() = default;

    virtual void accept(ExprVisitor& visitor) const = 0;
};

class ExprVisitor
{
public:
    virtual ~ExprVisitor() = default;

    virtual void visitBinaryExpr(const Binary& expr) = 0;
    virtual void visitGroupingExpr(const Grouping& expr) = 0;
    virtual void visitLiteralExpr(const Literal& expr) = 0;
    virtual void visitUnaryExpr(const Unary& expr) = 0;
};

