#include "GenerateAst.h"

#include <stdexcept>

void GenerateAst::defineAst(
    const fs::path& outputDir,
    const std::string& baseName,
    const std::vector<std::string>& types)
{
    fs::path outputFile = outputDir / (baseName + ".h");

    std::ofstream writer(outputFile);

    if (!writer.is_open())
    {
        throw std::runtime_error(
            "Unable to create file: " + outputFile.string());
    }

    writer << "#pragma once\n\n";

    writer << "#include <memory>\n";
    writer << "#include <string>\n";
    writer << "#include <variant>\n\n";

    writer << "#include \"Token.h\"\n\n";

    writer << "// ------------------------------------------------------------\n";
    writer << "// This file is auto-generated by GenerateAst.\n";
    writer << "// Do not edit manually.\n";
    writer << "// ------------------------------------------------------------\n\n";
}

void GenerateAst::defineVisitor(
    std::ofstream& writer,
    const std::string& baseName,
    const std::vector<std::string>& types)
{
    // TODO
}

void GenerateAst::defineType(
    std::ofstream& writer,
    const std::string& baseName,
    const std::string& className,
    const std::string& fieldList)
{
    // TODO
}