#include "GenerateAst.h"

std::string_view GenerateAst::trim(const std::string_view& str)
{
    const auto first = str.find_first_not_of(" \t");

    if (first == std::string_view::npos)
    {
        return {};
    }

    const auto last = str.find_last_not_of(" \t");

    return str.substr(first, last - first + 1);
}

GenerateAst::FieldInfo GenerateAst::parseField(std::string_view field)
{
    field = trim(field);

    const auto space = field.find_last_of(' ');

    if (space == std::string_view::npos)
    {
        throw std::runtime_error(
            "Invalid field declaration: " + std::string(field));
    }

    return {
        trim(field.substr(0, space)),
        trim(field.substr(space + 1))
    };
}

std::vector<GenerateAst::FieldInfo>
GenerateAst::parseFields(std::string_view fieldList)
{
    std::vector<FieldInfo> fields;

    while (!fieldList.empty())
    {
        const auto comma = fieldList.find(',');

        if (comma == std::string_view::npos)
        {
            fields.emplace_back(parseField(fieldList));
            break;
        }

        fields.emplace_back(
            parseField(fieldList.substr(0, comma)));

        fieldList.remove_prefix(comma + 1);
    }

    return fields;
}

void GenerateAst::generateHeader(
    std::ofstream& writer,
    const std::string& baseName,
    const std::vector<std::string>& types
)
{
       writer <<
R"(#pragma once

#include <memory>
#include <string>
#include <variant>

#include "scanner/Token.h"

// ------------------------------------------------------------
// This file is auto-generated by GenerateAst.
// Do not edit manually.
// ------------------------------------------------------------

)";

    writer << '\n';

    for (const auto& type : types)
    {
        const auto colon = type.find(':');

        std::string_view typeView{type};

        const auto className =
            trim(typeView.substr(0, colon));
        
        const auto fieldList =
            trim(typeView.substr(colon + 1));    
        
        defineType(
            writer,
            baseName,
            std::string(className),
            std::string(fieldList));       
    }

    writer << "\n";

    // Generate the base clase
    defineBaseClass(writer, baseName);

    // Generate the Visitor interface
    defineVisitor(writer, baseName, types);

}

void GenerateAst::generateSource(
    std::ofstream& writer,
    const std::string& baseName,
    const std::vector<std::string>& types
)
{
    writer << "#include \"ast/" << baseName << ".h\"\n\n";
}

void GenerateAst::defineAst(
    const fs::path& outputDirHeader,
    const fs::path& outputDirSource,
    const std::string& baseName,
    const std::vector<std::string>& types)
{
    fs::path outputFileHeader = outputDirHeader / (baseName + ".h");
    fs::path outputFileSource = outputDirSource / (baseName + ".cpp");

    std::ofstream writerHeader(outputFileHeader);
    std::ofstream writerSource(outputFileSource);

    if (!writerHeader.is_open())
    {
        throw std::runtime_error(
            "Unable to create file: " + outputFileHeader.string());
    }

      if (!writerSource.is_open())
    {
        throw std::runtime_error(
            "Unable to create file: " + outputFileSource.string());
    }

    generateHeader(writerHeader, baseName, types);
    generateSource(writerSource, baseName, types);

}

void GenerateAst::defineVisitor(
    std::ofstream& writer,
    const std::string& baseName,
    const std::vector<std::string>& types)
{
    writer << "class " << baseName << "Visitor\n";
    writer << "{\n";
    writer << "public:\n";
    writer << "    virtual ~" << baseName << "Visitor() = default;\n\n";

    for (const auto& type : types)
    {
        std::string_view view{type};

        const auto colon = view.find(':');
        const auto className = trim(view.substr(0, colon));

        writer
            << "    virtual void visit"
            << className
            << baseName
            << "(const "
            << className
            << "& expr) = 0;\n";
    }

    writer << "};\n\n";
}

void GenerateAst::defineBaseClass(
        std::ofstream& writer,
        const std::string& baseName)
{
    writer << "class " << baseName << "\n";
    writer << "{\n";

    writer << "public:\n";

    writer << "    virtual ~"
           << baseName
           << "() = default;\n\n";

    writer << "    virtual void accept("
           << baseName
           << "Visitor& visitor) const = 0;\n";

    writer << "};\n\n";
}

void GenerateAst::defineType(
    std::ofstream& writer,
    const std::string& baseName,
    const std::string& className,
    const std::string& fieldList)
{   
    const auto fields = parseFields(fieldList);

    writer << "class "
           << className
           << " : public "
           << baseName
           << "\n";

    writer << "{\n";

    writer << "    public:\n";

    writer << "        "
       << className
       << "(\n";

    for (std::size_t i = 0; i < fields.size(); ++i)
    {
        writer << "            "
            << fields[i].type
            << " "
            << fields[i].name;

        if (i + 1 != fields.size())
        {
            writer << ",";
        }

        writer << "\n";
    }   

    writer << "        );\n\n";
    
    writer << "\n";

    writer << "    private:\n";

    for (const auto& field : fields)
        {
            writer << "        "
                << field.type
                << " "
                << field.name
                << "_;\n";
        }


    writer << "    void accept("
       << baseName
       << "Visitor& visitor) const override\n";

    writer << "    {\n";

    writer << "        visitor.visit"
        << className
        << baseName
        << "(*this);\n";

    writer << "    }\n\n";
    writer << "};\n\n";  
}

